name: deploy-react-app
on:
  push:
    branches:
      - develop
      # - staging
      # - production
jobs:
  build-react-base:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v2
      - name: Installing Node.js
        uses: actions/setup-node@v2
      - name: Installing dependencies
        run: npm install
      - name: Building project
        if: ${{ github.ref_name == 'develop' }} #check branch to build environment
        run: npm run build:development
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

  deploy-s3:
    steps:
      - name: Deploy to S3 bucket develop
        if: ${{ github.ref_name == 'develop' }}
        run: aws s3 sync ./build/. s3://react-base-tqhuy